# Generated by Django 5.2.14 on 2026-05-25 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("roe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=255, unique=True)),
                (
                    "datasource_type",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("jira", "Jira")], db_index=True, default="gitlab", max_length=16
                    ),
                ),
                ("base_url", models.URLField(max_length=512)),
                ("encrypted_token_ciphertext", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("connected_user", models.CharField(blank=True, max_length=255)),
                ("visible_project_count", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("token_expiring", "Token expiring"),
                            ("token_expired", "Token expired"),
                            ("connection_error", "Connection error"),
                        ],
                        db_index=True,
                        default="connected",
                        max_length=32,
                    ),
                ),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("handle", models.CharField(blank=True, max_length=255)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="ingestion.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["datasource_id", "email"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("source_path", models.CharField(blank=True, max_length=512)),
                ("roe_slug", models.CharField(blank=True, max_length=255)),
                ("gitlab_project_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("source_url", models.URLField(blank=True, max_length=1024)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("initial_sync_queued", "Initial sync queued"),
                            ("syncing", "Syncing"),
                            ("active", "Active"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="initial_sync_queued",
                        max_length=32,
                    ),
                ),
                (
                    "sync_schedule",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("every_6h", "Every 6h"), ("daily", "Daily")],
                        default="hourly",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived"), ("orphaned", "Orphaned")],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_roe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_projects",
                        to="roe.rulesofengagement",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pinned_roe_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pinned_projects",
                        to="roe.rulesofengagementversion",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("cursor_to", models.DateTimeField(blank=True, null=True)),
                ("increments_ingested", models.IntegerField(default=0)),
                ("contributors_touched", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_runs_records",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="ingestion.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Increment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("commit", "Commit")], db_index=True, max_length=32)),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("summary", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="increments",
                        to="ingestion.contributor",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="increments_records",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="increments", to="ingestion.project"
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("datasource", "email"), name="ingestion_contributor_ds_email_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gitlab_project_id__isnull", False)),
                fields=("datasource", "gitlab_project_id"),
                name="ingestion_project_ds_gitlab_id_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="increment",
            index=models.Index(fields=["project", "occurred_at"], name="ingestion_i_project_18b50f_idx"),
        ),
        migrations.AddIndex(
            model_name="increment",
            index=models.Index(fields=["project", "kind", "occurred_at"], name="ingestion_i_project_4e587e_idx"),
        ),
        migrations.AddConstraint(
            model_name="increment",
            constraint=models.UniqueConstraint(
                fields=("project", "kind", "external_id"), name="ingestion_increment_proj_kind_ext_uniq"
            ),
        ),
    ]
