# Generated by Django 5.2.13 on 2026-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=255, unique=True)),
                (
                    "datasource_type",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("jira", "Jira")], db_index=True, default="gitlab", max_length=16
                    ),
                ),
                ("base_url", models.URLField(max_length=512)),
                ("encrypted_token_ciphertext", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("token_expiring", "Token expiring"),
                            ("token_expired", "Token expired"),
                            ("connection_error", "Connection error"),
                        ],
                        db_index=True,
                        default="connected",
                        max_length=32,
                    ),
                ),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
