# Generated by Django 5.2.13 on 2026-05-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial_datasource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("source_path", models.CharField(blank=True, max_length=512)),
                ("playbook_slug", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived"), ("orphaned", "Orphaned")],
                        db_index=True,
                        default="active",
                        max_length=32,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="ingestion.datasource"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
