# Generated by Django 5.2.14 on 2026-05-07 18:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_assigned_playbook(apps, schema_editor) -> None:
    Project = apps.get_model("ingestion", "Project")
    Playbook = apps.get_model("playbooks", "Playbook")
    for p in Project.objects.exclude(playbook_slug=""):
        raw = (p.playbook_slug or "").strip()
        if not raw:
            continue
        pb = Playbook.objects.filter(slug__iexact=raw).first()
        if pb is None:
            slugish = raw.lower().replace(" ", "-")
            pb = Playbook.objects.filter(slug__iexact=slugish).first()
        if pb is None:
            pb = Playbook.objects.filter(name__iexact=raw).first()
        if pb:
            p.assigned_playbook_id = pb.pk
            p.save(update_fields=["assigned_playbook_id"])


def noop_backfill_reverse(apps, schema_editor) -> None:
    """Forward-only backfill."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_beat_sync_due_projects"),
        ("playbooks", "0002_seed_featurefactory_playbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assigned_playbook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_projects",
                to="playbooks.playbook",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pinned_playbook_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_projects",
                to="playbooks.playbookversion",
            ),
        ),
        migrations.RunPython(backfill_assigned_playbook, noop_backfill_reverse),
    ]
