# Generated by Django 5.2.14 on 2026-05-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_project_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="connected_user",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="datasource",
            name="visible_project_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="datasource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="ingestion.datasource",
            ),
        ),
    ]
