# Generated by Django 5.x — Act 2 Projects fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0003_datasource_connected_user_project_set_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gitlab_project_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="source_url",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="project",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("initial_sync_queued", "Initial sync queued"),
                    ("syncing", "Syncing"),
                    ("active", "Active"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="initial_sync_queued",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sync_schedule",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("manual", "Manual only"),
                ],
                default="hourly",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="imported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(gitlab_project_id__isnull=False),
                fields=("datasource", "gitlab_project_id"),
                name="ingestion_project_ds_gitlab_id_uniq",
            ),
        ),
    ]
