# Generated by Django 5.2.14 on 2026-05-27 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0003_project_extended_sync_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionrun",
            name="milestones_ingested",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionrun",
            name="work_items_ingested",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("title", models.CharField(max_length=512)),
                ("state", models.CharField(db_index=True, max_length=32)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(db_index=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="milestones", to="ingestion.project"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("issue", "Issue"), ("merge_request", "Merge request")], db_index=True, max_length=32
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("iid", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=512)),
                ("state", models.CharField(db_index=True, max_length=32)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("record_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work",
                        to="ingestion.contributor",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units_of_work",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units_of_work",
                        to="ingestion.milestone",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units_of_work",
                        to="ingestion.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="UoWStateChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_state", models.CharField(blank=True, default="", max_length=32)),
                ("to_state", models.CharField(max_length=32)),
                ("recorded_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("source", models.CharField(default="gitlab", max_length=32)),
                (
                    "unit_of_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_changes",
                        to="ingestion.unitofwork",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                fields=("project", "external_id"), name="ingestion_milestone_proj_ext_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="unitofwork",
            index=models.Index(fields=["project", "kind", "updated_at"], name="ingestion_u_project_18b6f5_idx"),
        ),
        migrations.AddIndex(
            model_name="unitofwork",
            index=models.Index(fields=["project", "state"], name="ingestion_u_project_8a3b32_idx"),
        ),
        migrations.AddConstraint(
            model_name="unitofwork",
            constraint=models.UniqueConstraint(
                fields=("project", "kind", "external_id"), name="ingestion_uow_proj_kind_ext_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="uowstatechange",
            index=models.Index(fields=["unit_of_work", "recorded_at"], name="ingestion_u_unit_of_139a78_idx"),
        ),
    ]
