# Generated by Django 5.x — sync schedule: Every 6h replaces Manual

from django.db import migrations, models


def forwards_manual_to_every_6h(apps, schema_editor):
    Project = apps.get_model("ingestion", "Project")
    Project.objects.filter(sync_schedule="manual").update(sync_schedule="every_6h")


def backwards_every_6h_to_manual(apps, schema_editor):
    Project = apps.get_model("ingestion", "Project")
    Project.objects.filter(sync_schedule="every_6h").update(sync_schedule="manual")


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0004_project_act2_fields"),
    ]

    operations = [
        migrations.RunPython(forwards_manual_to_every_6h, backwards_every_6h_to_manual),
        migrations.AlterField(
            model_name="project",
            name="sync_schedule",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("every_6h", "Every 6h"),
                    ("daily", "Daily"),
                ],
                default="hourly",
                max_length=16,
            ),
        ),
    ]
