# Generated by Django 5.2.14 on 2026-05-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0005_project_sync_schedule_every6h"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("handle", models.CharField(blank=True, max_length=255)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="ingestion.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["datasource_id", "email"],
            },
        ),
        migrations.CreateModel(
            name="Increment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("commit", "Commit")], db_index=True, max_length=32)),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("summary", models.CharField(blank=True, max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="increments",
                        to="ingestion.contributor",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="increments_records",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="increments", to="ingestion.project"
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("cursor_to", models.DateTimeField(blank=True, null=True)),
                ("increments_ingested", models.IntegerField(default=0)),
                ("contributors_touched", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_runs_records",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="ingestion.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("datasource", "email"), name="ingestion_contributor_ds_email_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="increment",
            index=models.Index(fields=["project", "occurred_at"], name="ingestion_i_project_18b50f_idx"),
        ),
        migrations.AddIndex(
            model_name="increment",
            index=models.Index(fields=["project", "kind", "occurred_at"], name="ingestion_i_project_4e587e_idx"),
        ),
        migrations.AddConstraint(
            model_name="increment",
            constraint=models.UniqueConstraint(
                fields=("project", "kind", "external_id"), name="ingestion_increment_proj_kind_ext_uniq"
            ),
        ),
    ]
