# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0007_beat_sync_due_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
