"""SitRep model — narrative-phase implementation."""

from django.db import models


class SitRep(models.Model):
    """Situation Report generated by Gjallarhorn."""

    project = models.ForeignKey(
        "ingestion.Project",
        on_delete=models.CASCADE,
        related_name="sitreps",
    )
    generated_at = models.DateTimeField(auto_now_add=True, db_index=True)
    from_dt = models.DateTimeField()
    to_dt = models.DateTimeField()
    trigger = models.CharField(
        max_length=16,
        choices=[("automatic", "Automatic"), ("manual", "Manual")],
    )
    mode_at_generation = models.CharField(
        max_length=16,
        choices=[("semi_auto", "Semi-Auto"), ("auto", "Auto")],
        default="semi_auto",
    )
    roe_version = models.IntegerField(null=True, blank=True)
    headline = models.CharField(max_length=200)
    situation_assessment = models.TextField()
    fragos_applied = models.ManyToManyField(
        "sitrep.Frago",
        blank=True,
        related_name="sitreps_applied_to",
    )
    notable_activity = models.JSONField(default=list, blank=True)
    variables_snapshot = models.JSONField(default=list, blank=True)
    source_plan = models.ForeignKey(
        "gjallarhorn.ExecutionPlan",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        ordering = ["-generated_at"]
        indexes = [models.Index(fields=["project", "-generated_at"])]
        constraints = [
            models.UniqueConstraint(
                fields=["project", "to_dt"],
                name="uq_sitrep_project_to_dt",
            ),
        ]

    def __str__(self):
        return f"SitRep {self.pk} — {self.project.slug} @ {self.generated_at:%Y-%m-%d %H:%M}"
