# Generated by Django 5.2.14 on 2026-05-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SEED_SLUG = "featurefactory-roe"

WORKFLOW_MD = """## Roles

Donland — commander. Engineering leads own throughput and quality signals.

## OO / DA

Observe sync health and commit cadence; orient using Vitals; decide via SitRep;
act through FRAGOs when doctrine and reality diverge.
"""

VARIABLE_ROWS = [
    {
        "sort_order": 0,
        "name": "Transparency",
        "abbrev": "T",
        "calculating": "Freshness of ingested Increments vs sync SLA",
        "interpreting": "Green if last increment < 24h; orange 24–48h; red stale",
        "hover": "Whether we can trust the picture on the dashboard.",
    },
    {
        "sort_order": 1,
        "name": "Throughput",
        "abbrev": "TP",
        "calculating": "count(Increment where occurred_at in last_7d)",
        "interpreting": "WoW trend flat or up → green; sharp drop → orange",
        "hover": "Useful change landing per week (commits as proxy in MVP).",
    },
    {
        "sort_order": 2,
        "name": "Cycle & Lead Time",
        "abbrev": "CLT",
        "calculating": "median_lead_time(UnitOfWork closed in last_14d)",
        "interpreting": "<5d & not climbing → green; climbing → orange; >5d → red",
        "hover": "Flow efficiency signal from closed work items.",
    },
    {
        "sort_order": 3,
        "name": "Rework",
        "abbrev": "RW",
        "calculating": "reopen_rate(UnitOfWork last_30d)",
        "interpreting": "Low rework → green; spikes → orange/red",
        "hover": 'Quality of execution — surprises after "done".',
    },
    {
        "sort_order": 4,
        "name": "Quality",
        "abbrev": "Q",
        "calculating": "defect_density(last_30d)",
        "interpreting": "Below budget → green; at budget → orange; above → red",
        "hover": "Observable defects vs throughput.",
    },
    {
        "sort_order": 5,
        "name": "Complexity",
        "abbrev": "CX",
        "calculating": "weighted_files_changed_per_merge(last_14d)",
        "interpreting": "Stable → green; sharp climb → orange",
        "hover": "Structural churn risk in the codebase.",
    },
    {
        "sort_order": 6,
        "name": "Contribution",
        "abbrev": "CON",
        "calculating": "distinct_authors(Increment last_14d) / team_size",
        "interpreting": "Healthy spread → green; single-thread → orange",
        "hover": "Breadth of participation.",
    },
]


def seed_featurefactory_roe(apps, schema_editor) -> None:
    RulesOfEngagement = apps.get_model("playbooks", "RulesOfEngagement")
    RulesOfEngagementVersion = apps.get_model("playbooks", "RulesOfEngagementVersion")
    RulesOfEngagementVariable = apps.get_model("playbooks", "RulesOfEngagementVariable")

    if RulesOfEngagement.objects.filter(slug=SEED_SLUG).exists():
        return

    roe = RulesOfEngagement.objects.create(
        name="FeatureFactory RoE",
        slug=SEED_SLUG,
        description="Default seed doctrine — starter Variables for the Vitals tab.",
        is_system_seed=True,
    )
    ver = RulesOfEngagementVersion.objects.create(
        roe=roe,
        version_number=1,
        workflow_md=WORKFLOW_MD,
        change_summary="Seed RoE — starter Variables",
    )
    for row in VARIABLE_ROWS:
        RulesOfEngagementVariable.objects.create(roe_version=ver, **row)


def unseed_featurefactory_roe(apps, schema_editor) -> None:
    RulesOfEngagement = apps.get_model("playbooks", "RulesOfEngagement")
    RulesOfEngagement.objects.filter(slug=SEED_SLUG).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RulesOfEngagement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=512)),
                ("is_system_seed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbooks_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RulesOfEngagementVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("workflow_md", models.TextField(blank=True, default="")),
                ("change_summary", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbook_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="playbooks.rulesofengagement",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="RulesOfEngagementVariable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("abbrev", models.CharField(max_length=64)),
                ("calculating", models.TextField(blank=True, default="")),
                ("interpreting", models.TextField(blank=True, default="")),
                ("hover", models.TextField(blank=True, default="")),
                (
                    "roe_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="playbooks.rulesofengagementversion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="rulesofengagementversion",
            constraint=models.UniqueConstraint(
                fields=("roe", "version_number"), name="playbooks_rulesofengagementversion_unique_version_per_roe"
            ),
        ),
        migrations.RunPython(seed_featurefactory_roe, unseed_featurefactory_roe),
    ]
