# Generated by Django 5.2.14 on 2026-05-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rulesofengagementvariable",
            name="y_axis_label",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
