# Generated by Django 5.2.14 on 2026-05-07 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playbook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=512)),
                ("is_system_seed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbooks_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("workflow_md", models.TextField(blank=True, default="")),
                ("change_summary", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbook_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="playbooks.playbook"
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookVariable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("abbrev", models.CharField(max_length=64)),
                ("calculating", models.TextField(blank=True, default="")),
                ("interpreting", models.TextField(blank=True, default="")),
                ("hover", models.TextField(blank=True, default="")),
                ("dimensions", models.JSONField(default=list)),
                (
                    "playbook_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="playbooks.playbookversion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookTable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveSmallIntegerField()),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("unit_of_work", "UnitOfWork"),
                            ("increment", "Increment"),
                            ("milestone", "Milestone"),
                            ("sprint", "Sprint"),
                            ("contributor", "Contributor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("slicer", models.CharField(max_length=128)),
                ("dimensions", models.JSONField(default=list)),
                (
                    "playbook_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="playbooks.playbookversion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="playbookversion",
            constraint=models.UniqueConstraint(
                fields=("playbook", "version_number"), name="playbooks_playbookversion_unique_version_per_playbook"
            ),
        ),
    ]
