# Generated by Django 5.2.14 on 2026-05-12 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingestion", "0003_project_playbook_fks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("agent_identity", models.CharField(default="gjallarhorn", max_length=32)),
                ("conversation_type", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ingestion.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionPlan",
            fields=[
                ("plan_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("goal", models.TextField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=5)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_type", models.CharField(blank=True, max_length=255)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                ("progress_current", models.IntegerField(default=0)),
                ("progress_total", models.IntegerField(default=0)),
                ("progress_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plans", to="gjallarhorn.conversation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=16)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="gjallarhorn.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanStep",
            fields=[
                ("step_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.IntegerField()),
                ("action", models.TextField()),
                ("reasoning_why_needed", models.TextField()),
                ("expected_outcome", models.TextField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("result", models.JSONField(blank=True, null=True)),
                ("outcome_assessment", models.TextField(blank=True)),
                ("is_critical", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="gjallarhorn.executionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(fields=("user", "project"), name="uniq_conversation_user_project"),
        ),
        migrations.AddConstraint(
            model_name="planstep",
            constraint=models.UniqueConstraint(fields=("plan", "order"), name="uq_plan_step_order"),
        ),
    ]
