# Generated by Django 5.2.14 on 2026-05-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gjallarhorn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionplan",
            name="sitrep_from_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionplan",
            name="sitrep_to_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionplan",
            name="sitrep_trigger",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
