# Generated by Django 5.2.14 on 2026-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gjallarhorn", "0002_sitrep_plan_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionplan",
            name="planning_model",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="planstep",
            name="is_planning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planstep",
            name="model_used",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
