# Generated by Django 5.2.14 on 2026-05-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gjallarhorn", "0002_recover_orphaned_plans_beat"),
    ]

    operations = [
        migrations.AddField(
            model_name="planstep",
            name="is_variable_assessment",
            field=models.BooleanField(default=False),
        ),
    ]
