# Generated by Django 5.2.14 on 2026-05-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gjallarhorn", "0003_sitrep_model_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="planstep",
            name="tool",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
