# Generated by Django 5.2.14 on 2026-05-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gjallarhorn", "0001_initial"),
        ("ingestion", "0001_initial"),
        ("playbooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SituationalAwareness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name_plural": "Situational awareness records",
            },
        ),
        migrations.CreateModel(
            name="Frago",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("body_md", models.TextField(blank=True, default="")),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_variable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fragos",
                        to="playbooks.rulesofengagementvariable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fragos_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fragos", to="ingestion.project"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fragos_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="FragoAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("enabled_toggled", "Enable/disable toggled"),
                            ("revoked", "Revoked"),
                            ("bulk_activated", "Bulk activated"),
                            ("bulk_deactivated", "Bulk deactivated"),
                            ("bulk_revoked", "Bulk revoked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.CharField(max_length=512)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frago_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "frago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="sitrep.frago"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SituationalAwarenessVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("standing_md", models.TextField(blank=True, default="")),
                ("active_md", models.TextField(blank=True, default="")),
                ("change_summary", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awareness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="sitrep.situationalawareness",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="situational_awareness_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="SituationalAwarenessEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(choices=[("standing", "Standing"), ("active", "Active")], max_length=16)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(default="Content", max_length=255)),
                ("body_md", models.TextField(blank=True, default="")),
                ("decision_label", models.CharField(blank=True, default="", max_length=128)),
                ("decision_href", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="situational_awareness_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="sitrep.situationalawarenessversion",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SitRep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("generated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("from_dt", models.DateTimeField()),
                ("to_dt", models.DateTimeField()),
                (
                    "trigger",
                    models.CharField(choices=[("automatic", "Automatic"), ("manual", "Manual")], max_length=16),
                ),
                (
                    "mode_at_generation",
                    models.CharField(
                        choices=[("semi_auto", "Semi-Auto"), ("auto", "Auto")], default="semi_auto", max_length=16
                    ),
                ),
                ("roe_version", models.IntegerField(blank=True, null=True)),
                ("headline", models.CharField(max_length=200)),
                ("situation_assessment", models.TextField()),
                ("notable_activity", models.JSONField(blank=True, default=list)),
                (
                    "fragos_applied",
                    models.ManyToManyField(blank=True, related_name="sitreps_applied_to", to="sitrep.frago"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sitreps", to="ingestion.project"
                    ),
                ),
                (
                    "source_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gjallarhorn.executionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [models.Index(fields=["project", "-generated_at"], name="sitrep_sitr_project_08da3a_idx")],
                "constraints": [models.UniqueConstraint(fields=("project", "to_dt"), name="uq_sitrep_project_to_dt")],
            },
        ),
        migrations.AddConstraint(
            model_name="situationalawarenessversion",
            constraint=models.UniqueConstraint(
                fields=("awareness", "version_number"),
                name="sitrep_situationalawarenessversion_unique_version_per_awareness",
            ),
        ),
    ]
