# Generated by Django 5.2.14 on 2026-05-07 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0003_project_playbook_fks"),
        ("sitrep", "0001_frago_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SituationalAwareness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situational_awareness",
                        to="ingestion.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Situational awareness records",
            },
        ),
        migrations.CreateModel(
            name="SituationalAwarenessVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("standing_md", models.TextField(blank=True, default="")),
                ("active_md", models.TextField(blank=True, default="")),
                ("change_summary", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awareness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="sitrep.situationalawareness",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="situational_awareness_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("awareness", "version_number"),
                        name="sitrep_situationalawarenessversion_unique_version_per_awareness",
                    )
                ],
            },
        ),
    ]
