# Generated by Django 5.2.14 on 2026-05-26 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gjallarhorn", "0003_planstep_is_variable_assessment"),
        ("roe", "0002_rulesofengagementvariable_y_axis_label"),
        ("sitrep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitrep",
            name="variables_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="VariableDatapoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("variable_name", models.CharField(max_length=255)),
                ("y_axis_label", models.CharField(blank=True, default="", max_length=128)),
                ("value", models.CharField(blank=True, max_length=64, null=True)),
                ("color", models.CharField(max_length=16)),
                ("from_dt", models.DateTimeField()),
                ("to_dt", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roe_variable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datapoints",
                        to="roe.rulesofengagementvariable",
                    ),
                ),
                (
                    "sitrep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="datapoints", to="sitrep.sitrep"
                    ),
                ),
                (
                    "source_plan_step",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="gjallarhorn.planstep"
                    ),
                ),
            ],
            options={
                "ordering": ["sitrep", "roe_variable__sort_order"],
                "constraints": [
                    models.UniqueConstraint(fields=("sitrep", "roe_variable"), name="uq_vdp_sitrep_roe_variable")
                ],
            },
        ),
    ]
