# Generated by Django 5.2.14 on 2026-05-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitrep", "0002_situational_awareness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FragoAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("enabled_toggled", "Enable/disable toggled"),
                            ("revoked", "Revoked"),
                            ("bulk_activated", "Bulk activated"),
                            ("bulk_deactivated", "Bulk deactivated"),
                            ("bulk_revoked", "Bulk revoked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.CharField(max_length=512)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frago_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "frago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="sitrep.frago"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
