# Generated by Django 5.2.14 on 2026-05-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_entries_from_md(apps, schema_editor) -> None:
    Version = apps.get_model("sitrep", "SituationalAwarenessVersion")
    Entry = apps.get_model("sitrep", "SituationalAwarenessEntry")
    for v in Version.objects.all():
        if (v.standing_md or "").strip():
            Entry.objects.create(
                version=v,
                section="standing",
                sort_order=0,
                title="Standing context",
                body_md=v.standing_md,
            )
        if (v.active_md or "").strip():
            Entry.objects.create(
                version=v,
                section="active",
                sort_order=0,
                title="Content",
                body_md=v.active_md,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("sitrep", "0003_frago_audit_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SituationalAwarenessEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(choices=[("standing", "Standing"), ("active", "Active")], max_length=16)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(default="Content", max_length=255)),
                ("body_md", models.TextField(blank=True, default="")),
                ("decision_label", models.CharField(blank=True, default="", max_length=128)),
                ("decision_href", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="situational_awareness_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="sitrep.situationalawarenessversion",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "sort_order", "pk"],
            },
        ),
        migrations.RunPython(backfill_entries_from_md, migrations.RunPython.noop),
    ]
