# Generated by Django 5.2.14 on 2026-05-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gjallarhorn", "0001_initial"),
        ("ingestion", "0003_project_playbook_fks"),
        ("sitrep", "0005_situational_awareness_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitRep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("generated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("from_dt", models.DateTimeField()),
                ("to_dt", models.DateTimeField()),
                (
                    "trigger",
                    models.CharField(choices=[("automatic", "Automatic"), ("manual", "Manual")], max_length=16),
                ),
                (
                    "mode_at_generation",
                    models.CharField(
                        choices=[("semi_auto", "Semi-Auto"), ("auto", "Auto")], default="semi_auto", max_length=16
                    ),
                ),
                ("playbook_version", models.IntegerField(blank=True, null=True)),
                ("headline", models.CharField(max_length=200)),
                ("situation_assessment", models.TextField()),
                ("notable_activity", models.JSONField(blank=True, default=list)),
                (
                    "fragos_applied",
                    models.ManyToManyField(blank=True, related_name="sitreps_applied_to", to="sitrep.frago"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sitreps", to="ingestion.project"
                    ),
                ),
                (
                    "source_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gjallarhorn.executionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [models.Index(fields=["project", "-generated_at"], name="sitrep_sitr_project_08da3a_idx")],
                "constraints": [models.UniqueConstraint(fields=("project", "to_dt"), name="uq_sitrep_project_to_dt")],
            },
        ),
    ]
